name: streamlivr
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  animated_custom_dropdown: ^1.5.0
  animated_snack_bar: ^0.3.1
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  dotted_line: ^3.1.0
  # file_picker: ^5.3.2
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.9
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.6
  flutter_switch: ^0.3.2
  glass_kit: ^2.0.1
  google_fonts: ^4.0.4
  http: ^0.13.6
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  lottie: ^2.3.2
  provider: ^6.0.3
  random_date: ^0.0.7
  shared_preferences: ^2.1.1
  unique_name_generator: ^1.0.0
  zego_uikit_prebuilt_live_streaming: ^2.12.5
  day_night_themed_switch: ^1.0.0
  syncfusion_flutter_barcodes: ^22.1.37

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#001D50"
    theme_color: "#001D50"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/.
    - assets/icons/.
    - assets/animations/.
flutter_assets:
  assets_path: assets/
  output_path: lib/assets/
  filename: assets.dart
