name: streamlivr
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_animated_dialog: ^2.0.1
  flutter_otp_text_field: ^1.1.1
  flutter_svg: ^2.0.6
  google: ^0.0.1
  google_fonts: ^4.0.4
  http: ^0.13.6
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  lottie: ^2.3.2
  provider: ^6.0.3
  shared_preferences: ^2.1.1
  animated_custom_dropdown: ^1.5.0
  animated_snack_bar: ^0.3.1
  dotted_line: ^3.1.0
  file_picker: ^5.3.0
  glass_kit: ^2.0.1
  flutter_switch: ^0.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/.
    - assets/icons/.
    - assets/animations/.
flutter_assets:
  assets_path: assets/
  output_path: lib/assets/
  filename: assets.dart

