// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // TODO(Lyokone): Remove when FlutterFire CLI updated
      case TargetPlatform.windows:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo5Tstpw1Dckl0nKSQGPLyfTLJh2SgQ2g',
    appId: '1:688095053609:android:eb52647d89726f11259938',
    messagingSenderId: '529057152207',
    projectId: 'streamlivr-1cc43',
    storageBucket: 'streamlivr-1cc43.appspot.com',
    authDomain: 'flutterfire-e2e-tests.firebaseapp.com',
    measurementId: 'G-JN95N1JV2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5Tstpw1Dckl0nKSQGPLyfTLJh2SgQ2g',
    appId: '1:688095053609:android:eb52647d89726f11259938',
    messagingSenderId: '529057152207',
    projectId: 'streamlivr-1cc43',
    storageBucket: 'streamlivr-1cc43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5Tstpw1Dckl0nKSQGPLyfTLJh2SgQ2g',
    appId: '1:688095053609:android:eb52647d89726f11259938',
    messagingSenderId: '529057152207',
    projectId: 'streamlivr-1cc43',
    storageBucket: 'streamlivr-1cc43.appspot.com',
    databaseURL:
        'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    androidClientId:
        '406099696497-tvtvuiqogct1gs1s6lh114jeps7hpjm5.apps.googleusercontent.com',
    iosClientId:
        '406099696497-taeapvle10rf355ljcvq5dt134mkghmp.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.tests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5Tstpw1Dckl0nKSQGPLyfTLJh2SgQ2g',
    appId: '1:529057152207:android:510e6f7b8cb1fc51908bba',
    messagingSenderId: '529057152207',
    projectId: 'streamlivr-1cc43',
    storageBucket: 'streamlivr-1cc43.appspot.com',
    databaseURL:
        'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    androidClientId:
        '406099696497-tvtvuiqogct1gs1s6lh114jeps7hpjm5.apps.googleusercontent.com',
    iosClientId:
        '406099696497-taeapvle10rf355ljcvq5dt134mkghmp.apps.googleusercontent.com',
    iosBundleId: 'io.flutter.plugins.firebase.tests',
  );
}
